import type { Metadata } from 'next'
import '@/styles/globals.css'
import { sportingGrotesque } from '@/helpers/fonts.helper'
import PageHeader from '@/components/layout/navbar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${sportingGrotesque.className} antialiased`}>
        <PageHeader />
        {children}
      </body>
    </html>
  )
}
