import type { Metadata } from 'next'
import '@/styles/globals.css'
import { sportingGrotesque } from '@/helpers/fonts.helper'
import PageHeader from '@/components/layout/navbar'
import FooterSection from '@/components/layout/footer'
import Providers from '@/components/providers'

export const metadata: Metadata = {
  title: {
    template: '%s | devlop.me',
    default: 'devlop.me',
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${sportingGrotesque.className} antialiased`}>
        <Providers>
          <PageHeader />
          {children}
          <FooterSection />
        </Providers>
      </body>
    </html>
  )
}
